config/routes.rb
Rails.application.routes.draw do
  root to: 'products#index'
  resources :products

  get "/datadump", to: "invupdates#index"
  post "/datadump", to: "invupdates#create"
  delete "/datadump", to: "invupdates#destroy"

  resources :orders, only: [:create]

  get 'text', to: 'texts#index'

end

app/models/customer.rb
class Customer < ActiveRecord::Base
  has_many :units
  has_many :orders

  enum conversation_state: [:start, :determine_product, :product_confirmed, :order_confirmed]
end

app/models/invupdate.rb
class Invupdate < ActiveRecord::Base
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :product
  belongs_to :customer
end

app/models/product.rb
class Product < ActiveRecord::Base

  def self.find_product_by_range(crgb_hash)
    green = {c: (3800..4300), r: (800..1200), g: (1900..2100), b: (1000..1300)}
    red = {c: (4200..4800), r: (2500..2900), g: (700..1200), b: (700..1200)}
    blue = {c: (7900..8400), r: (1200..1600), g: (2800..3200), b: (3400..4200)}

    rcolor = 'green' if green[:c] === crgb_hash[:c_value] && green[:r] === crgb_hash[:r_value] && green[:g] === crgb_hash[:g_value] && green[:b] === crgb_hash[:b_value]
    rcolor = 'red' if red[:c] === crgb_hash[:c_value] && red[:r] === crgb_hash[:r_value] && red[:g] === crgb_hash[:g_value] && red[:b] === crgb_hash[:b_value]
    rcolor = 'blue' if blue[:c] === crgb_hash[:c_value] && blue[:r] === crgb_hash[:r_value] && blue[:g] === crgb_hash[:g_value] && blue[:b] === crgb_hash[:b_value]
    rcolor ||= ''
    rcolor
  end

end

app/models/unit.rb
class Unit < ActiveRecord::Base
  belongs_to :customer

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session
end

app/controllers/invupdates_controller.rb
class InvupdatesController < ApplicationController
  before_action :set_invupdate, only: [:show, :edit, :update, :destroy]

  def index
    @invupdates = Invupdate.all
  end

  def show
    #@invupdate = Invupdate.find_by(params[:id])
  end

  def new
    @invupdate = Invupdate.new
  end

  def edit
  end

  def create
    @invupdate = Invupdate.new(invupdate_params)
    @invupdate.save
    product_color = Product.find_product_by_range(invupdate_params)
    @product = Product.find_by_color(product_color)
    if @product.nil?
      head :no_content
    else
      @product.quantity -= 1 unless @product.nil?
      @product.save unless @product.nil?
      render "show.json.jbuilder", status: :created
    end

      #Define our value ranges
    #Determine what color values are recieved
    #compare them to our defined ranges
    #return a color
    #(@invupdate.c_value == int && @invupdate.r_value == int && @invupdate.g_value == int && @invupdate.b_value == int)
    # find product by color and subtract 1 from quantity
    # if (@invupdate.c_value == [3301..3800])
    #   color = "red"
    # elsif (@invupdate.c_value == [2800..3299])
    #   color = "green"
    # elsif (@invupdate.c_value == [5700..6400])
    #   color = "blue"
    # end
    # product = Product.find_by(color: color)
    # product.update(quantity: product.quantity - 1 )

    # respond_to do |format|
    #   if @invupdate.save
    #     #format.html { notice: 'Invupdate was successfully created.' }
    #     format.json { render :show, status: :created, location: @invupdate }
    #   else
    #     format.html { render :new }
    #     format.json { render json: @invupdate.errors, status: :unprocessable_entity }
    #   end
    end
  end

  def update
    respond_to do |format|
      if @invupdate.update(invupdate_params)
        format.html { redirect_to @invupdate, notice: 'Invupdate was successfully updated.' }
        format.json { render :show, status: :ok, location: @invupdate }
      else
        format.html { render :edit }
        format.json { render json: @invupdate.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @invupdate.destroy
    respond_to do |format|
      format.html { redirect_to invupdates_url, notice: 'Invupdate was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_invupdate
      @invupdate = Invupdate.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def invupdate_params
      params.fetch(:invupdate, {})
      params.permit(:unit_id, :c_value, :r_value, :g_value, :b_value)
    end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController



end

app/controllers/product_controller.rb
class ProductController < ApplicationController
  
  def index

  end

  def new
    @product = Product.new
    render :new
  end

  def create
    @product = Product.new( name: params[:name],
                            quantity: params[:quantity].to_i,
                            rvalue: params[:rvalue].to_i,
                            gvalue: params[:gvalue].to_i,
                            bvalue: params[:bvalue].to_i)
    if @product.save
      respond_to do |format|
        format.html
        format.json
      end
    end
  end

  def edit
  end

  def update
  end

  def destroy
    product = Product.find(params[:id])
    flash[:notice] = "The product has been removed from the inventory list."
    product.destroy
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  
  def index

  end

  def new
    @product = Product.new
    render :new
  end

  def create
    @product = Product.new( name: params[:name],
                            quantity: params[:quantity].to_i,
                            )
    if @product.save
      respond_to do |format|
        format.html
        format.json
      end
    end
  end

  def edit
  end

  def update
  end

  def destroy
    product = Product.find(params[:id])
    flash[:notice] = "The products has been removed from the inventory list."
    product.destroy
  end
end

app/controllers/texts_controller.rb
class TextsController < ApplicationController

  def index
    # Parameters: {"ToCountry"=>"US",
    #              "ToState"=>"GA",
    #              "SmsMessageSid"=>"SMecadf0061ffb938491ccfc1164a1e2fc",
    #              "NumMedia"=>"0", "ToCity"=>"COLUMBUS", "FromZip"=>"32801",
    #              "SmsSid"=>"SMecadf0061ffb938491ccfc1164a1e2fc",
    #              "FromState"=>"FL", "SmsStatus"=>"received", "FromCity"=>"ORLANDO", "Body"=>"Hey", "FromCountry"=>"US",
    #              "To"=>"+16787862528", "ToZip"=>"31901", "NumSegments"=>"1",
    #              "MessageSid"=>"SMecadf0061ffb938491ccfc1164a1e2fc", "AccountSid"=>"AC389ab8c76fd5d42343da183110d741e8",
    #              "From"=>"+14072837742", "ApiVersion"=>"2010-04-01"}

    phone_number = params['From']
    customer = Customer.find_by_phone(phone_number)

    if customer.start? || customer.conversation_state.nil? || customer.order_confirmed?
      product = Product.find_by_name(params['Body'].titleize)
      message = "Hey #{customer.first_name}!  It's great to hear that you need more #{product.name.titleize}.  Please reply 1 to CONFIRM or 2 to CANCEL."
      session['product'] = product.name
      customer.update(conversation_state: Customer.conversation_states[:determine_product], conversation_id: params['MessageSid'])
    elsif customer.determine_product?
      product = Product.find_by_name(session['product'])
      response = params['Body'].to_i
      if response == 1
        customer.update(conversation_state: Customer.conversation_states[:product_confirmed], conversation_id: params['MessageSid'])
        message = "Stock Request for #{session['product']}: Please reply with a quantity."
      else
        customer.update(conversation_state: Customer.conversation_states[:start], conversation_id: params['MessageSid'])
        message = "Stock Request for #{session['product']} Cancelled."
      end
    elsif customer.product_confirmed?
      quantity = params['Body'].to_i
      product = Product.find_by_name(session['product'])
      customer.update(conversation_state: Customer.conversation_states[:order_confirmed], conversation_id: params['MessageSid'])
      order = Order.create(customer_id: customer.id, product: product, quantity: quantity)
      message = "Order #{order.id} created for Product: #{product.name} - Quantity: #{quantity}.  Thanks for using StockMyCooler powered by Coca-Cola!"
    else

    end

    twiml = Twilio::TwiML::Response.new do |r|
      r.Message message
    end
    render xml: twiml.text
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/invupdates_helper.rb
module InvupdatesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/invupdates/_form.html.erb
<%= form_for(@invupdate) do |f| %>
  <% if @invupdate.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@invupdate.errors.count, "error") %> prohibited this invupdate from being saved:</h2>

      <ul>
      <% @invupdate.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/invupdates/edit.html.erb
<h1>Editing Invupdate</h1>

<%= render 'form' %>

<%= link_to 'Show', @invupdate %> |
<%= link_to 'Back', invupdates_path %>

app/views/invupdates/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Invupdates</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @invupdates.each do |invupdate| %>
      <tr>
        <td><%= link_to 'Show', invupdate %></td>
        <td><%= link_to 'Edit', edit_invupdate_path(invupdate) %></td>
        <td><%= link_to 'Destroy', invupdate, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Invupdate', new_invupdate_path %>

app/views/invupdates/new.html.erb
<h1>New Invupdate</h1>

<%= render 'form' %>

<%= link_to 'Back', invupdates_path %>

app/views/invupdates/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_invupdate_path(@invupdate) %> |
<%= link_to 'Back', invupdates_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Coolscandeluxe</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/products/create.html.erb
<h1>Product#create</h1>
<p>Find me in app/views/product/create.html.erb</p>

app/views/products/destroy.html.erb
<h1>Product#destroy</h1>
<p>Find me in app/views/product/destroy.html.erb</p>

app/views/products/edit.html.erb
<h1>Product#edit</h1>
<p>Find me in app/views/product/edit.html.erb</p>

app/views/products/index.html.erb
<h1>Product#index</h1>
<p>Find me in app/views/product/index.html.erb</p>

app/views/products/new.html.erb
<h1>Product#new</h1>
<p>Find me in app/views/product/new.html.erb</p>

app/views/products/show.html.erb
<h1>Product#show</h1>
<p>Find me in app/views/product/show.html.erb</p>

app/views/products/update.html.erb
<h1>Product#update</h1>
<p>Find me in app/views/product/update.html.erb</p>